paths:
  data: ../data/fiveK
  train: ../data/fiveK/train-list-subset.txt
  test: ../data/fiveK/test-list-grad-cam.txt
  checkpoints: ../model/checkpoints/resetnet50_scratch
  unetcheckpoints: ../model/checkpoints/unet_mse_3
model:
  #  name could be one of the following:
  # 1. resnet18
  # 2. resnet34
  # 3. resnet50
  name: resnet50
  # type could be one of the following:
  # 1. FINE_TUNE: fine-tune the model
  # 2. FEATURE_EXTRACTOR: use the model as a feature extractor
  # 3. TRAIN_FROM_SCRATCH : train the model from scratch
  type: TRAIN_FROM_SCRATCH
  num_classes: 5
  lr: 0.1
  momentum: 0.9
  num_epochs: 1
unetmodel:
  loss: mse
  depth: 3
  lr: 0.01
  num_classes: 5
  num_epochs: 1




